package h2;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import kotlin.jvm.functions.Function0;
import kotlin.reflect.KProperty;
import kotlin.reflect.jvm.internal.impl.descriptors.ClassDescriptor;
import kotlin.reflect.jvm.internal.impl.descriptors.ConstructorDescriptor;
import kotlin.reflect.jvm.internal.impl.resolve.scopes.MemberScope;
import n2.AbstractC0718j;

/* JADX INFO: renamed from: h2.s, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes2.dex */
public final class C0515s extends kotlin.jvm.internal.i implements Function0 {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final /* synthetic */ int f3430a;
    public final /* synthetic */ C0522z b;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ C0515s(C0522z c0522z, int i) {
        super(0);
        this.f3430a = i;
        this.b = c0522z;
    }

    @Override // kotlin.jvm.functions.Function0
    public final Object invoke() throws InvocationTargetException {
        C0522z c0522z = this.b;
        switch (this.f3430a) {
            case 0:
                Collection collectionC = c0522z.c();
                ArrayList arrayList = new ArrayList(kotlin.collections.o.D(collectionC));
                Iterator it = collectionC.iterator();
                while (it.hasNext()) {
                    arrayList.add(new F(c0522z, (ConstructorDescriptor) it.next()));
                }
                return arrayList;
            case 1:
                return c0522z.f(c0522z.getDescriptor().getDefaultType().getMemberScope(), 1);
            case 2:
                MemberScope staticScope = c0522z.getDescriptor().getStaticScope();
                kotlin.jvm.internal.h.e(staticScope, "descriptor.staticScope");
                return c0522z.f(staticScope, 1);
            case 3:
                int i = C0522z.d;
                L2.b bVarN = c0522z.n();
                C0519w c0519w = (C0519w) c0522z.c.invoke();
                c0519w.getClass();
                KProperty kProperty = AbstractC0496A.b[0];
                Object objInvoke = c0519w.f3362a.invoke();
                kotlin.jvm.internal.h.e(objInvoke, "<get-moduleData>(...)");
                boolean z6 = bVarN.c;
                X2.g gVar = ((s2.h) objInvoke).f4772a;
                ClassDescriptor classDescriptorB = z6 ? gVar.b(bVarN) : AbstractC0718j.d(gVar.b, bVarN);
                if (classDescriptorB != null) {
                    return classDescriptorB;
                }
                Class cls = c0522z.b;
                s2.e eVarA = s2.d.a(cls);
                F2.a aVar = eVarA != null ? eVarA.b.f352a : null;
                switch (aVar == null ? -1 : AbstractC0520x.f3451a[aVar.ordinal()]) {
                    case -1:
                    case 6:
                        throw new N1.d(androidx.constraintlayout.core.motion.a.j(cls, "Unresolved class: "), 2);
                    case 0:
                    default:
                        throw new C0.x();
                    case 1:
                    case 2:
                    case 3:
                        throw new UnsupportedOperationException(androidx.constraintlayout.core.motion.a.j(cls, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "));
                    case 4:
                        throw new UnsupportedOperationException(androidx.constraintlayout.core.motion.a.j(cls, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "));
                    case 5:
                        throw new N1.d("Unknown class: " + cls + " (kind = " + aVar + ')', 2);
                }
            case 4:
                return c0522z.f(c0522z.getDescriptor().getDefaultType().getMemberScope(), 2);
            case 5:
                MemberScope staticScope2 = c0522z.getDescriptor().getStaticScope();
                kotlin.jvm.internal.h.e(staticScope2, "descriptor.staticScope");
                return c0522z.f(staticScope2, 2);
            case 6:
                if (c0522z.b.isAnonymousClass()) {
                    return null;
                }
                L2.b bVarN2 = c0522z.n();
                if (bVarN2.c) {
                    return null;
                }
                return bVarN2.b().b();
            default:
                return new C0519w(c0522z);
        }
    }
}
